name: Auto Commit & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to prevent push issues

      - name: Set up Git
        run: |
          git config --global user.email "handmadejewellery2003@gmail.com"
          git config --global user.name "handmadejewellery"

      - name: Auto Commit and Push
        run: |
          git add .
          git commit -m "Auto-update" || echo "No changes to commit"
          git push origin main
